### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by henryreed** [akalin/cryptopals-python3#3]
Hello!

Awesome work! Really love this repo.

I was wondering if you could add a license to allow for code reuse? Personally I am a fan of [Creative Commons Zero v1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/), since it's equivalent to waiving copyright in countries where it's legal and, where it's not, it falls back to a "[public domain equivalent license](https://en.wikipedia.org/wiki/Public_domain_equivalent_license)."

Let me know if you have any questions! Looking forward to your response.

**Comment by akalin** [comment]
Picked the MIT license. Sorry for the delay!
